import { IEmployeeFormType } from "../types/Employees";

export const EMPLOYEE_FORM_DEFAULT_DATA: IEmployeeFormType = {
    firstName: {
        key: 'firstName',
        label: 'Firstname',
        error: false,
        errorMessage: 'First name is required',
        required: true,
        value: '',
        type: 'text',
    },
    lastName: {
        key: 'lastName',
        label: 'Lastname',
        error: false,
        errorMessage: 'Last name is required',
        required: true,
        value: '',
        type: 'text',
    },
    address: {
        key: 'address',
        label: 'Address',
        required: false,
        value: '',
        type: 'text',
    },
    salary: {
        key: 'salary',
        label: 'Salary',
        error: false,
        errorMessage: 'Please enter salary',
        required: true,
        value: 10000,
        type: 'number',
    },
    pincode: {
        key: 'pincode',
        label: 'Pincode',
        error: false,
        errorMessage: 'Please Enter Pincode',
        required: true,
        value: '',
        type: 'number',
    },
    joiningDate: {
        key: 'joiningDate',
        label: 'Joining Date',
        error: false,
        errorMessage: 'Please select joining Date',
        required: true,
        value: new Date().toISOString(),
        type: 'date',
    },
    // imageUrl: {
    //     key: 'imageUrl',
    //     label: 'Profile Picture',
    //     required: false,
    //     value: '',
    //     type: 'text',
    // },
    emailAddress: {
        key: 'emailAddress',
        label: 'Email',
        error: false,
        errorMessage: 'Please enter email address',
        required: true,
        value: '',
        type: 'text',
    },
    category: {
        key: 'category',
        label: 'Category',
        error: false,
        errorMessage: 'Please select category',
        required: true,
        value: '',
        type: 'dropdown',
        options: [],
        dropdownId: '',
    },
    phoneNumber: {
        key: 'phoneNumber',
        label: 'Contact Number',
        error: false,
        errorMessage: 'Please provide contact number',
        required: true,
        value: '',
        type: 'number',
    },
}